matrix:
  include: 
    - os: linux  
      dist: xenial
      compiler: gcc
      addons:
        apt:
          packages:
            - python3-numpy 
            - python3-sympy
            - libsbml5-python
            - python3-ipdb 
            - python3-matplotlib
    - os: osx
      compiler: clang

install:
    - pyenv versions
    - pyenv shell 2.7 3.6
    - pip3 install --user sympy python-libsbml numpy matplotlib ipdb
    - models/runCI.sh

notifications:
  email: false
