matrix:
  include: 
    - os: linux  
      dist: xenial
      compiler: gcc
      env: PYENV_VERSION=3.6
      addons:
        apt:
          packages:
            - python3-numpy 
            - python3-sympy
            - libsbml5-python
            - python3-ipdb 
            - python3-matplotlib


install:
    - pip3 install --user sympy python-libsbml numpy matplotlib ipdb
    - models/runCI.sh

notifications:
  email: false
