language: generic
cache: pip

matrix:
  include: 
    - os: linux  
      dist: xenial
      compiler: gcc
      addons:
        apt:
          packages:
            - gfortran
            - python3-numpy 
            - python3-sympy
            - libsbml5-python
            - python3-ipdb 
            - python3-matplotlib
    - os: linux  
      dist: xenial
      compiler: clang
    - os: osx
      compiler: gcc
      osx_image: xcode9.3
    - os: osx
      compiler: gcc
      osx_image: xcode9.2
    - os: osx
      compiler: gcc
      osx_image: xcode9.1
    - os: osx
      compiler: gcc
      osx_image: xcode9
    - os: osx
      compiler: gcc
      osx_image: xcode8.3
  allow_failures:
    - os: osx
      compiler: gcc
      osx_image: xcode8.3

install:
    - export BASE_DIR=`pwd`
#    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update; fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew upgrade python; fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew install gcc || brew link --overwrite gcc; fi
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then export F77=gfortran; fi
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then pyenv versions; fi
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then pyenv shell 2.7 3.6; fi
    - pip3 install --user sympy python-libsbml numpy matplotlib ipdb

script:
    - cd $BASE_DIR
    - misc/runCI.sh
    # test if all result plots have been generated
    - test `ls $BASE_DIR/BirthDeath*pdf | wc -l` = 7
    
after_failure:
    - ls -alR
    
notifications:
  email: false
