language: generic
cache: pip

matrix:
  include: 
    - os: linux  
      dist: xenial
      compiler: gcc
      addons:
        apt:
          packages:
            - python3-numpy 
            - python3-sympy
            - libsbml5-python
            - python3-ipdb 
            - python3-matplotlib
    - os: osx
      compiler: clang
#  allow_failures:
#    - os: osx
#      compiler: clang

install:
    - export BASE_DIR=`pwd`
    - if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew upgrade python; fi
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then pyenv versions; fi
    - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then pyenv shell 2.7 3.6; fi
    - pip3 install --user sympy python-libsbml numpy matplotlib ipdb

script:
    - cd $BASE_DIR
    - models/runCI.sh
    # test if all result plots have been generated
    - test `ls $BASE_DIR/BirthDeath*pdf | wc -l` = 7
    
after_failure:
    - ls -alR
    
notifications:
  email: false
