matrix:
  include: 
    - os: linux  
      dist: xenial
      compiler: gcc
      addons:
        apt:
          packages:
            - python3-numpy 
            - python3-sympy
            - libsbml5-python
            - python3-ipdb 
            - python3-matplotlib
        
install:
    - pip3 install --user sympy 
    - models/runCI.sh
