function d2AdThetadPhi = d2AdThetadPhi(in1,t,in3) %#codegen
%D2ADTHETADPHI
%    D2ADTHETADPHI = D2ADTHETADPHI(IN1,T,IN3)

%    This function was generated by the Symbolic Math Toolbox version 6.1.
%    21-Nov-2014 14:20:15

d2AdThetadPhi = reshape([0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0],[24, 2]);
