function dAdPhi = dAdPhi(in1,t,in3) %#codegen
%DADPHI
%    DADPHI = DADPHI(IN1,T,IN3)

%    This function was generated by the Symbolic Math Toolbox version 6.1.
%    21-Nov-2014 14:19:50

dAdPhi = reshape([0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0],[4, 2]);
