function J = J(in1,t,in3) %#codegen
%J
%    J = J(IN1,T,IN3)

%    This function was generated by the Symbolic Math Toolbox version 6.1.
%    21-Nov-2014 14:19:49

g_m = in3(:,3);
g_p = in3(:,4);
k_p = in3(:,2);
J = reshape([0.0,g_m,k_p,0.0,0.0,0.0,0.0,g_p],[4, 2]);
