function F = reactionFlux(in1,t,in3) %#codegen
%REACTIONFLUX
%    F = REACTIONFLUX(IN1,T,IN3)

%    This function was generated by the Symbolic Math Toolbox version 6.1.
%    21-Nov-2014 14:19:48

g_m = in3(:,3);
g_p = in3(:,4);
k_m = in3(:,1);
k_p = in3(:,2);
m = in1(:,1);
p = in1(:,2);
F = [k_m,g_m.*m,k_p.*m,g_p.*p];
