function systemJacobian = systemJacobian(in1,t,in3) %#codegen
%SYSTEMJACOBIAN
%    SYSTEMJACOBIAN = SYSTEMJACOBIAN(IN1,T,IN3)

%    This function was generated by the Symbolic Math Toolbox version 6.1.
%    21-Nov-2014 14:19:52

g_m = in3(:,3);
g_p = in3(:,4);
k_p = in3(:,2);
m = in1(:,1);
p = in1(:,2);
t2 = g_m.*m;
t3 = sqrt(t2);
t4 = conj(t3);
t5 = k_p.*m;
t6 = sqrt(t5);
t7 = conj(t6);
t8 = g_p.*p;
t9 = sqrt(t8);
t10 = conj(t9);
systemJacobian = reshape([-g_m,k_p,(g_m.*t3.*(1.0./2.0))./t4+g_m.*1.0./sqrt(t2).*t4.*(1.0./2.0),0.0,(k_p.*t6.*(1.0./2.0))./t7+k_p.*1.0./sqrt(t5).*t7.*(1.0./2.0),0.0,0.0,0.0,0.0,0.0,-g_p,0.0,0.0,(g_p.*t9.*(1.0./2.0))./t10+g_p.*1.0./sqrt(t8).*t10.*(1.0./2.0),0.0,0.0,0.0,0.0,0.0,0.0,g_m.*-2.0,k_p,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,k_p,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,g_p.*-2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-g_m,k_p,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-g_p,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-g_m,k_p,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-g_p],[9, 9]);
