/*
 * d2EdPhi2.c
 *
 * Code generation for function 'd2EdPhi2'
 *
 */

/* Include files */
#include "rt_nonfinite.h"
#include "Afunc.h"
#include "Efunc.h"
#include "J.h"
#include "MI.h"
#include "S0.h"
#include "S20.h"
#include "S2V0.h"
#include "SV0.h"
#include "V0.h"
#include "Y0.h"
#include "d2AdPhi2.h"
#include "d2AdPhidTheta.h"
#include "d2AdTheta2.h"
#include "d2AdThetadPhi.h"
#include "d2EdPhi2.h"
#include "d2EdPhidTheta.h"
#include "d2EdTheta2.h"
#include "d2EdThetadPhi.h"
#include "d2fdTheta2.h"
#include "dAdPhi.h"
#include "dAdTheta.h"
#include "dEdPhi.h"
#include "dEdTheta.h"
#include "dFdTheta.h"
#include "reactionFlux.h"
#include "systemJacobian.h"
#include "reactionFlux_rtwutil.h"

/* Function Definitions */
void d2EdPhi2(const double in1[2], double t, const double in3[6], double
              b_d2EdPhi2[32])
{
  double x[32];
  (void)t;

  /* D2EDPHI2 */
  /*     D2EDPHI2 = D2EDPHI2(IN1,T,IN3) */
  /*     This function was generated by the Symbolic Math Toolbox version 6.1. */
  /*     19-Nov-2014 22:37:48 */
  x[0] = 0.0;
  x[1] = 0.0;
  x[2] = in3[2] * in3[2] / rt_powd_snf(in3[2] * in1[0], 1.5) * 0.25;
  x[3] = 0.0;
  x[4] = 0.0;
  x[5] = in3[1] * in3[1] / rt_powd_snf(in3[1] * in1[0], 1.5) * -0.25;
  x[6] = 0.0;
  x[7] = 0.0;
  x[8] = 0.0;
  x[9] = 0.0;
  x[10] = 0.0;
  x[11] = 0.0;
  x[12] = 0.0;
  x[13] = 0.0;
  x[14] = 0.0;
  x[15] = 0.0;
  x[16] = 0.0;
  x[17] = 0.0;
  x[18] = 0.0;
  x[19] = 0.0;
  x[20] = 0.0;
  x[21] = 0.0;
  x[22] = 0.0;
  x[23] = 0.0;
  x[24] = 0.0;
  x[25] = 0.0;
  x[26] = 0.0;
  x[27] = 0.0;
  x[28] = 0.0;
  x[29] = 0.0;
  x[30] = 0.0;
  x[31] = in3[3] * in3[3] / rt_powd_snf(in3[3] * in1[1], 1.5) * 0.25;
  memcpy(&b_d2EdPhi2[0], &x[0], sizeof(double) << 5);
}

/* End of code generation (d2EdPhi2.c) */
