/*
 * S20.c
 *
 * Code generation for function 'S20'
 *
 */

/* Include files */
#include "rt_nonfinite.h"
#include "Afunc.h"
#include "Efunc.h"
#include "J.h"
#include "MI.h"
#include "S0.h"
#include "S20.h"
#include "S2V0.h"
#include "SV0.h"
#include "V0.h"
#include "Y0.h"
#include "d2AdPhi2.h"
#include "d2AdPhidTheta.h"
#include "d2AdTheta2.h"
#include "d2AdThetadPhi.h"
#include "d2EdPhi2.h"
#include "d2EdPhidTheta.h"
#include "d2EdTheta2.h"
#include "d2EdThetadPhi.h"
#include "d2fdTheta2.h"
#include "dAdPhi.h"
#include "dAdTheta.h"
#include "dEdPhi.h"
#include "dEdTheta.h"
#include "dFdTheta.h"
#include "reactionFlux.h"
#include "systemJacobian.h"
#include "reactionFlux_rtwutil.h"

/* Function Definitions */
void S20(const double in1[6], double out1[72])
{
  double t2;
  double t3;
  double t4;
  double t5;
  double t6;
  double t7;
  double t8;
  double x[72];

  /* S20 */
  /*     OUT1 = S20(IN1) */
  /*     This function was generated by the Symbolic Math Toolbox version 6.1. */
  /*     21-Nov-2014 14:19:56 */
  t2 = 1.0 / (in1[2] * in1[2]);
  t3 = 1.0 / in1[3];
  t4 = 1.0 / in1[2];
  t5 = t3 * t4;
  t6 = 1.0 / (in1[3] * in1[3]);
  t7 = 1.0 / rt_powd_snf(in1[2], 3.0);
  t8 = in1[0] * in1[1] * t2 * t6;
  x[0] = 0.0;
  x[1] = 0.0;
  x[2] = 0.0;
  x[3] = t5;
  x[4] = -t2;
  x[5] = -in1[1] * t2 * t3;
  x[6] = 0.0;
  x[7] = -in1[1] * t4 * t6;
  x[8] = 0.0;
  x[9] = 0.0;
  x[10] = 0.0;
  x[11] = 0.0;
  x[12] = 0.0;
  x[13] = t5;
  x[14] = 0.0;
  x[15] = 0.0;
  x[16] = 0.0;
  x[17] = -in1[0] * t2 * t3;
  x[18] = 0.0;
  x[19] = -in1[0] * t4 * t6;
  x[20] = 0.0;
  x[21] = 0.0;
  x[22] = 0.0;
  x[23] = 0.0;
  x[24] = -t2;
  x[25] = -in1[1] * t2 * t3;
  x[26] = 0.0;
  x[27] = -in1[0] * t2 * t3;
  x[28] = in1[0] * t7 * 2.0;
  x[29] = in1[0] * in1[1] * t3 * t7 * 2.0;
  x[30] = 0.0;
  x[31] = t8;
  x[32] = 0.0;
  x[33] = 0.0;
  x[34] = 0.0;
  x[35] = 0.0;
  x[36] = 0.0;
  x[37] = -in1[1] * t4 * t6;
  x[38] = 0.0;
  x[39] = -in1[0] * t4 * t6;
  x[40] = 0.0;
  x[41] = t8;
  x[42] = 0.0;
  x[43] = 1.0 / rt_powd_snf(in1[3], 3.0) * in1[0] * in1[1] * t4 * 2.0;
  x[44] = 0.0;
  x[45] = 0.0;
  x[46] = 0.0;
  x[47] = 0.0;
  x[48] = 0.0;
  x[49] = 0.0;
  x[50] = 0.0;
  x[51] = 0.0;
  x[52] = 0.0;
  x[53] = 0.0;
  x[54] = 0.0;
  x[55] = 0.0;
  x[56] = 0.0;
  x[57] = 0.0;
  x[58] = 0.0;
  x[59] = 0.0;
  x[60] = 0.0;
  x[61] = 0.0;
  x[62] = 0.0;
  x[63] = 0.0;
  x[64] = 0.0;
  x[65] = 0.0;
  x[66] = 0.0;
  x[67] = 0.0;
  x[68] = 0.0;
  x[69] = 0.0;
  x[70] = 0.0;
  x[71] = 0.0;
  memcpy(&out1[0], &x[0], 72U * sizeof(double));
}

/* End of code generation (S20.c) */
