/*
 * SV0.c
 *
 * Code generation for function 'SV0'
 *
 */

/* Include files */
#include "rt_nonfinite.h"
#include "Afunc.h"
#include "Efunc.h"
#include "J.h"
#include "MI.h"
#include "S0.h"
#include "S20.h"
#include "S2V0.h"
#include "SV0.h"
#include "V0.h"
#include "Y0.h"
#include "d2AdPhi2.h"
#include "d2AdPhidTheta.h"
#include "d2AdTheta2.h"
#include "d2AdThetadPhi.h"
#include "d2EdPhi2.h"
#include "d2EdPhidTheta.h"
#include "d2EdTheta2.h"
#include "d2EdThetadPhi.h"
#include "d2fdTheta2.h"
#include "dAdPhi.h"
#include "dAdTheta.h"
#include "dEdPhi.h"
#include "dEdTheta.h"
#include "dFdTheta.h"
#include "reactionFlux.h"
#include "systemJacobian.h"

/* Function Definitions */
void SV0(const double in1[6], double out1[18])
{
  double t2;
  double t4;
  double t5;
  double t6;
  double t8;
  double t9;
  double t10;
  double t12;
  double t14;
  double t16;
  double t19;
  double t22;
  double t23;
  double t24;
  double t27;
  double t28;
  double t29;
  double t31;
  double t32;
  double t34;
  double t35;
  double t37;
  double t45;
  double t47;
  double t48;
  double x[18];

  /* SV0 */
  /*     OUT1 = SV0(IN1) */
  /*     This function was generated by the Symbolic Math Toolbox version 6.1. */
  /*     21-Nov-2014 14:19:55 */
  t2 = sqrt(in1[0]);
  t4 = 1.0 / in1[2];
  t5 = in1[2] * in1[4];
  t6 = sqrt(t5);
  t8 = 1.0 / sqrt(t5);
  t9 = 1.0 / t6;
  t10 = 1.0 / sqrt(in1[0]);
  t12 = 1.0 / t2;
  t14 = t2 * t10 * 0.5 + t2 * t12 * 0.5;
  t5 = in1[2] + in1[3];
  t16 = 1.0 / t5;
  t19 = t2 * t2 + t6 * t6;
  t22 = in1[4] * t6 * t8 * 0.5 + in1[4] * t6 * t9 * 0.5;
  t23 = 1.0 / (in1[2] * in1[2]);
  t24 = 1.0 / (t5 * t5);
  t27 = in1[2] * t6 * t8 * 0.5 + in1[2] * t6 * t9 * 0.5;
  t28 = in1[1] * in1[1];
  t29 = 1.0 / in1[3];
  t5 = in1[1] * in1[4];
  t31 = in1[2] * in1[2];
  t32 = sqrt(t5);
  t34 = 1.0 / sqrt(t5);
  t35 = 1.0 / t32;
  t5 = in1[3] * in1[5];
  t37 = sqrt(t5);
  t45 = ((((t2 * t2 * t28 + t31 * t37 * t37) + t6 * t6 * t28) + t31 * t32 * t32)
         + in1[2] * in1[3] * t37 * t37) + in1[2] * in1[3] * t32 * t32;
  t5 = 1.0 / sqrt(t5);
  t47 = 1.0 / t37;
  t48 = in1[3] * in1[3];
  x[0] = t4 * t14 * 0.5;
  x[1] = in1[1] * t4 * t14 * t16 * 0.5;
  x[2] = t4 * t16 * t29 * (t2 * t10 * t28 * 0.5 + t2 * t12 * t28 * 0.5) * 0.5;
  x[3] = 0.0;
  x[4] = t4 * t16 * t19 * 0.5;
  x[5] = t4 * t16 * t29 * (((((in1[1] * t2 * t2 * 2.0 + in1[1] * t6 * t6 * 2.0)
    + in1[4] * t31 * t32 * t35 * 0.5) + in1[4] * t31 * t32 * t34 * 0.5) + in1[2]
    * in1[3] * in1[4] * t32 * t35 * 0.5) + in1[2] * in1[3] * in1[4] * t32 * t34 *
    0.5) * 0.5;
  x[6] = t4 * t22 * 0.5 - t19 * t23 * 0.5;
  x[7] = (in1[1] * t4 * t16 * t22 * 0.5 - in1[1] * t4 * t19 * t24 * 0.5) - in1[1]
    * t16 * t19 * t23 * 0.5;
  x[8] = (t4 * t16 * t29 * (((((in1[2] * t32 * t32 * 2.0 + in1[2] * t37 * t37 *
    2.0) + in1[3] * t32 * t32) + in1[3] * t37 * t37) + in1[4] * t6 * t9 * t28 *
            0.5) + in1[4] * t6 * t8 * t28 * 0.5) * 0.5 - t4 * t24 * t29 * t45 *
          0.5) - t16 * t23 * t29 * t45 * 0.5;
  x[9] = 0.0;
  x[10] = in1[1] * t4 * t19 * t24 * -0.5;
  x[11] = (t4 * t24 * t29 * t45 * -0.5 - 1.0 / (in1[3] * in1[3]) * t4 * t16 *
           t45 * 0.5) + t4 * t16 * t29 * (((((in1[2] * t32 * t32 + in1[2] * t37 *
    t37) + in1[5] * t31 * t37 * t47 * 0.5) + in1[5] * t31 * t37 * t5 * 0.5) +
    in1[2] * in1[3] * in1[5] * t37 * t47 * 0.5) + in1[2] * in1[3] * in1[5] * t37
    * t5 * 0.5) * 0.5;
  x[12] = t4 * t27 * 0.5;
  x[13] = in1[1] * t4 * t16 * t27 * 0.5;
  x[14] = t4 * t16 * t29 * (((((in1[2] * t6 * t9 * t28 * 0.5 + in1[2] * t6 * t8 *
    t28 * 0.5) + in1[1] * t31 * t32 * t35 * 0.5) + in1[1] * t31 * t32 * t34 *
    0.5) + in1[2] * in1[3] * in1[1] * t32 * t35 * 0.5) + in1[2] * in1[3] * in1[1]
    * t32 * t34 * 0.5) * 0.5;
  x[15] = 0.0;
  x[16] = 0.0;
  x[17] = t4 * t16 * t29 * (((in1[2] * t37 * t47 * t48 * 0.5 + in1[2] * t37 * t5
    * t48 * 0.5) + in1[3] * t31 * t37 * t47 * 0.5) + in1[3] * t31 * t37 * t5 *
    0.5) * 0.5;
  memcpy(&out1[0], &x[0], 18U * sizeof(double));
}

/* End of code generation (SV0.c) */
