function d2AdPhidTheta = d2AdPhidTheta(in1,t,in3) %#codegen
%D2ADPHIDTHETA
%    D2ADPHIDTHETA = D2ADPHIDTHETA(IN1,T,IN3)

%    This function was generated by the Symbolic Math Toolbox version 6.1.
%    19-Nov-2014 22:38:07

d2AdPhidTheta = reshape([0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0],[8, 6]);
