function A = Afunc(in1,t,in3) %#codegen
%AFUNC
%    A = AFUNC(IN1,T,IN3)

%    This function was generated by the Symbolic Math Toolbox version 6.1.
%    25-Nov-2014 23:18:29

g_m = in3(:,3);
g_p = in3(:,4);
k_p = in3(:,2);
A = reshape([-g_m,k_p,0.0,-g_p],[2, 2]);
