function d2AdPhi2 = d2AdPhi2(in1,t,in3) %#codegen
%D2ADPHI2
%    D2ADPHI2 = D2ADPHI2(IN1,T,IN3)

%    This function was generated by the Symbolic Math Toolbox version 6.1.
%    25-Nov-2014 23:18:30

d2AdPhi2 = reshape([0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0],[8, 2]);
