function d2EdPhi2 = d2EdPhi2(in1,t,in3) %#codegen
%D2EDPHI2
%    D2EDPHI2 = D2EDPHI2(IN1,T,IN3)

%    This function was generated by the Symbolic Math Toolbox version 6.1.
%    03-Dec-2014 08:03:55

g_m = in3(:,3);
g_p = in3(:,4);
k_p = in3(:,2);
m = in1(:,1);
p = in1(:,2);
d2EdPhi2 = reshape([0.0,0.0,g_m.^2.*1.0./(g_m.*m).^(3.0./2.0).*(1.0./4.0),0.0,0.0,k_p.^2.*1.0./(k_p.*m).^(3.0./2.0).*(-1.0./4.0),0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,g_p.^2.*1.0./(g_p.*p).^(3.0./2.0).*(1.0./4.0)],[16, 2]);
