function dAdTheta = dAdTheta(in1,t,in3) %#codegen
%DADTHETA
%    DADTHETA = DADTHETA(IN1,T,IN3)

%    This function was generated by the Symbolic Math Toolbox version 6.1.
%    25-Nov-2014 23:18:29

dAdTheta = reshape([0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,-1.0,0.0,0.0,0.0,0.0,0.0,0.0,-1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0],[4, 6]);
