function dAdTheta = dAdTheta(in1,t,in3) %#codegen
%DADTHETA
%    DADTHETA = DADTHETA(IN1,T,IN3)

%    This function was generated by the Symbolic Math Toolbox version 6.1.
%    03-Dec-2014 08:03:54

dAdTheta = reshape([0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,-1.0,0.0,0.0,0.0,0.0,0.0,0.0,-1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0],[4, 6]);
