function dFdTheta = dFdTheta(in1,t,in3) %#codegen
%DFDTHETA
%    DFDTHETA = DFDTHETA(IN1,T,IN3)

%    This function was generated by the Symbolic Math Toolbox version 6.1.
%    25-Nov-2014 23:18:28

m = in1(:,1);
p = in1(:,2);
dFdTheta = reshape([1.0,0.0,0.0,0.0,0.0,0.0,m,0.0,0.0,m,0.0,0.0,0.0,0.0,0.0,p,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0],[4, 6]);
