function E = Efunc(in1,t,in3) %#codegen
%EFUNC
%    E = EFUNC(IN1,T,IN3)

%    This function was generated by the Symbolic Math Toolbox version 6.1.
%    03-Dec-2014 08:03:55

g_m = in3(:,3);
g_p = in3(:,4);
k_m = in3(:,1);
k_p = in3(:,2);
m = in1(:,1);
p = in1(:,2);
E = reshape([sqrt(k_m),0.0,-sqrt(g_m.*m),0.0,0.0,sqrt(k_p.*m),0.0,-sqrt(g_p.*p)],[2, 4]);
