function out1 = SV0(in1) %#codegen
%SV0
%    OUT1 = SV0(IN1)

%    This function was generated by the Symbolic Math Toolbox version 6.1.
%    03-Dec-2014 08:03:56

g_m = in1(:,3);
g_p = in1(:,4);
k_m = in1(:,1);
k_p = in1(:,2);
t2 = 1.0./g_m;
t3 = g_m+g_p;
t4 = 1.0./t3;
t5 = 1.0./g_m.^2;
t6 = 1.0./t3.^2;
t7 = 1.0./g_p;
t8 = g_m+g_p+k_p;
t9 = k_m.*k_p.*t2.*t4.*t7;
out1 = reshape([t2,k_p.*t2.*t4,k_p.*t2.*t4.*t7.*t8,0.0,k_m.*t2.*t4,t9+k_m.*t2.*t4.*t7.*t8,-k_m.*t5,-k_m.*k_p.*t2.*t6-k_m.*k_p.*t4.*t5,t9-k_m.*k_p.*t2.*t6.*t7.*t8-k_m.*k_p.*t4.*t5.*t7.*t8,0.0,-k_m.*k_p.*t2.*t6,t9-k_m.*k_p.*t2.*t6.*t7.*t8-1.0./g_p.^2.*k_m.*k_p.*t2.*t4.*t8,0.0,0.0,0.0,0.0,0.0,0.0],[3, 6]);
