function systemJacobian = systemJacobian(in1,t,in3) %#codegen
%SYSTEMJACOBIAN
%    SYSTEMJACOBIAN = SYSTEMJACOBIAN(IN1,T,IN3)

%    This function was generated by the Symbolic Math Toolbox version 6.1.
%    03-Dec-2014 08:03:56

g_m = in3(:,3);
g_p = in3(:,4);
k_p = in3(:,2);
systemJacobian = reshape([-g_m,k_p,g_m,0.0,k_p,0.0,0.0,0.0,0.0,0.0,-g_p,0.0,0.0,g_p,0.0,0.0,0.0,0.0,0.0,0.0,g_m.*-2.0,k_p,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-g_m-g_p,k_p.*2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,g_p.*-2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-g_m,k_p,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-g_p,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-g_m,k_p,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-g_p],[9, 9]);
