function out1 = V0(in1) %#codegen
%V0
%    OUT1 = V0(IN1)

%    This function was generated by the Symbolic Math Toolbox version 6.1.
%    25-Nov-2014 23:18:33

g_m = in1(:,3);
g_p = in1(:,4);
k_m = in1(:,1);
k_p = in1(:,2);
phi01 = in1(:,5);
phi02 = in1(:,6);
t2 = sqrt(k_m);
t3 = g_m.*phi01;
t4 = sqrt(t3);
t5 = 1.0./g_m;
t6 = conj(t2);
t7 = t2.*t6;
t8 = conj(t4);
t9 = t4.*t8;
t10 = t7+t9;
t11 = g_m+g_p;
t12 = 1.0./t11;
t13 = g_p.*phi02;
t14 = sqrt(t13);
t15 = k_p.^2;
t16 = g_m.^2;
t17 = k_p.*phi01;
t18 = sqrt(t17);
t19 = conj(t14);
t20 = conj(t18);
out1 = [t5.*t10.*(1.0./2.0);k_p.*t5.*t10.*t12.*(1.0./2.0);(t5.*t12.*(t2.*t6.*t15+t4.*t8.*t15+t14.*t16.*t19+t16.*t18.*t20+g_m.*g_p.*t14.*t19+g_m.*g_p.*t18.*t20).*(1.0./2.0))./g_p];
