function out1 = V0(in1) %#codegen
%V0
%    OUT1 = V0(IN1)

%    This function was generated by the Symbolic Math Toolbox version 6.1.
%    03-Dec-2014 08:03:56

g_m = in1(:,3);
g_p = in1(:,4);
k_m = in1(:,1);
k_p = in1(:,2);
t2 = 1.0./g_m;
t3 = g_m+g_p;
t4 = 1.0./t3;
out1 = [k_m.*t2;k_m.*k_p.*t2.*t4;(k_m.*k_p.*t2.*t4.*(g_m+g_p+k_p))./g_p];
