function out1 = Y0(in1) %#codegen
%Y0
%    OUT1 = Y0(IN1)

%    This function was generated by the Symbolic Math Toolbox version 6.1.
%    25-Nov-2014 23:18:33

g_m = in1(:,3);
g_p = in1(:,4);
k_m = in1(:,1);
k_p = in1(:,2);
t2 = 1.0./g_m;
out1 = [k_m.*t2,(k_m.*k_p.*t2)./g_p];
