/*
 * Afunc.c
 *
 * Code generation for function 'Afunc'
 *
 */

/* Include files */
#include "rt_nonfinite.h"
#include "Afunc.h"
#include "Efunc.h"
#include "J.h"
#include "MI.h"
#include "S0.h"
#include "S20.h"
#include "S2V0.h"
#include "SV0.h"
#include "V0.h"
#include "Y0.h"
#include "d2AdPhi2.h"
#include "d2AdPhidTheta.h"
#include "d2AdTheta2.h"
#include "d2AdThetadPhi.h"
#include "d2EdPhi2.h"
#include "d2EdPhidTheta.h"
#include "d2EdTheta2.h"
#include "d2EdThetadPhi.h"
#include "d2fdTheta2.h"
#include "dAdPhi.h"
#include "dAdTheta.h"
#include "dEdPhi.h"
#include "dEdTheta.h"
#include "dFdTheta.h"
#include "reactionFlux.h"
#include "systemJacobian.h"

/* Function Definitions */
void Afunc(const double in1[2], double t, const double in3[6], double A[4])
{
  double x[4];
  int k;
  (void)in1;
  (void)t;

  /* AFUNC */
  /*     A = AFUNC(IN1,T,IN3) */
  /*     This function was generated by the Symbolic Math Toolbox version 6.1. */
  /*     25-Nov-2014 23:18:29 */
  x[0] = -in3[2];
  x[1] = in3[1];
  x[2] = 0.0;
  x[3] = -in3[3];
  for (k = 0; k < 4; k++) {
    A[k] = x[k];
  }
}

/* End of code generation (Afunc.c) */
