/*
 * MI.c
 *
 * Code generation for function 'MI'
 *
 */

/* Include files */
#include "rt_nonfinite.h"
#include "Afunc.h"
#include "Efunc.h"
#include "J.h"
#include "MI.h"
#include "S0.h"
#include "S20.h"
#include "S2V0.h"
#include "SV0.h"
#include "V0.h"
#include "Y0.h"
#include "d2AdPhi2.h"
#include "d2AdPhidTheta.h"
#include "d2AdTheta2.h"
#include "d2AdThetadPhi.h"
#include "d2EdPhi2.h"
#include "d2EdPhidTheta.h"
#include "d2EdTheta2.h"
#include "d2EdThetadPhi.h"
#include "d2fdTheta2.h"
#include "dAdPhi.h"
#include "dAdTheta.h"
#include "dEdPhi.h"
#include "dEdTheta.h"
#include "dFdTheta.h"
#include "reactionFlux.h"
#include "systemJacobian.h"

/* Function Definitions */
void MI(const double in1[2], double t, const double in3[6], double b_gamma,
        double b_MI[81])
{
  double t4;
  double t7;
  double t8;
  double t9;
  double t13;
  double t14;
  double t15;
  double t16;
  double t18;
  double t19;
  double t20;
  double t22;
  double t24;
  double t25;
  double t26;
  double t27;
  double t28;
  double t29;
  double t30;
  double t31;
  double t32;
  double t35;
  double t36;
  double x[81];
  (void)t;

  /* MI */
  /*     MI = MI(IN1,T,IN3,GAMMA) */
  /*     This function was generated by the Symbolic Math Toolbox version 6.1. */
  /*     25-Nov-2014 23:18:32 */
  t4 = 1.0 / (in3[2] * b_gamma + 1.0);
  t7 = 1.0 / (in3[3] * b_gamma + 1.0);
  t8 = in3[2] * in1[0];
  t9 = sqrt(t8);
  t13 = 1.0 / (in3[2] * b_gamma * 2.0 + 1.0);
  t14 = 1.0 / t9;
  t15 = 1.0 / sqrt(t8);
  t16 = t9 * t9;
  t8 += t16;
  t18 = in3[3] * in1[1];
  t19 = in3[1] * in1[0];
  t20 = sqrt(t18);
  t22 = sqrt(t19);
  t24 = b_gamma * b_gamma;
  t25 = in3[1] * in3[1];
  t26 = t22 * t22;
  t27 = in3[3] * in3[3];
  t28 = in3[2] * in3[2];
  t29 = t24 * t24;
  t30 = t20 * t20;
  t31 = 1.0 / t20;
  t32 = 1.0 / sqrt(t18);
  t35 = 1.0 / (in3[3] * b_gamma * 2.0 + 1.0);
  t36 = b_gamma * in3[1] * t4 * t7;
  x[0] = t4;
  x[1] = t36;
  x[2] = in3[2] * b_gamma * t4 * t13 * t14 * t15 * t8 * 0.5;
  x[3] = in3[2] * in3[1] * t4 * t13 * t14 * t15 * t8 * t24 * 0.5;
  x[4] = t4 * t7 * t13 * t14 * t15 / sqrt(t19) * t31 * t32 * t35 *
    (((((((((((((((b_gamma * in3[1] * t9 * t9 * t20 * t20 * t26 + b_gamma * in1
                   [0] * t9 * t9 * t20 * t20 * t25) + in3[2] * in3[1] * t9 * t9 *
                  t20 * t20 * t24 * t26 * 2.0) + in3[3] * in3[1] * t9 * t9 * t20
                 * t20 * t24 * t26) + in3[3] * in3[1] * t9 * t9 * t22 * t22 *
                t24 * t30) + in3[2] * in1[0] * t9 * t9 * t20 * t20 * t24 * t25 *
               2.0) + in3[3] * in1[0] * t9 * t9 * t20 * t20 * t24 * t25) + in3[1]
             * in1[1] * t9 * t9 * t22 * t22 * t24 * t27) + in3[2] * in3[3] * t16
            * t20 * t20 * t22 * t22 * t25 * t29) + in3[2] * b_gamma * t16 * t20 *
           t20 * t22 * t22 * t24 * t25) + in3[3] * in1[0] * t20 * t20 * t22 *
          t22 * t25 * t28 * t29) + b_gamma * in1[0] * t20 * t20 * t22 * t22 *
         t24 * t25 * t28) + in3[2] * in3[3] * b_gamma * in3[1] * t9 * t9 * t20 *
        t20 * t24 * t26 * 2.0) + in3[2] * in3[3] * b_gamma * in3[1] * t9 * t9 *
       t22 * t22 * t24 * t30 * 2.0) + in3[2] * in3[3] * b_gamma * in1[0] * t9 *
      t9 * t20 * t20 * t24 * t25 * 2.0) + in3[2] * b_gamma * in3[1] * in1[1] *
     t9 * t9 * t22 * t22 * t24 * t27 * 2.0) * 0.5 / t22;
  x[5] = 0.0;
  x[6] = 0.0;
  x[7] = 0.0;
  x[8] = 0.0;
  x[9] = 0.0;
  x[10] = t7;
  x[11] = 0.0;
  x[12] = 0.0;
  x[13] = in3[3] * b_gamma * t7 * t31 * t32 * t35 * (t18 + t30) * 0.5;
  x[14] = 0.0;
  x[15] = 0.0;
  x[16] = 0.0;
  x[17] = 0.0;
  x[18] = 0.0;
  x[19] = 0.0;
  x[20] = t13;
  x[21] = b_gamma * in3[1] * t13;
  x[22] = t13 * t24 * t25 * t35;
  x[23] = 0.0;
  x[24] = 0.0;
  x[25] = 0.0;
  x[26] = 0.0;
  x[27] = 0.0;
  x[28] = 0.0;
  x[29] = 0.0;
  x[30] = 1.0;
  x[31] = b_gamma * in3[1] * t35;
  x[32] = 0.0;
  x[33] = 0.0;
  x[34] = 0.0;
  x[35] = 0.0;
  x[36] = 0.0;
  x[37] = 0.0;
  x[38] = 0.0;
  x[39] = 0.0;
  x[40] = t35;
  x[41] = 0.0;
  x[42] = 0.0;
  x[43] = 0.0;
  x[44] = 0.0;
  x[45] = 0.0;
  x[46] = 0.0;
  x[47] = 0.0;
  x[48] = 0.0;
  x[49] = 0.0;
  x[50] = t4;
  x[51] = t36;
  x[52] = 0.0;
  x[53] = 0.0;
  x[54] = 0.0;
  x[55] = 0.0;
  x[56] = 0.0;
  x[57] = 0.0;
  x[58] = 0.0;
  x[59] = 0.0;
  x[60] = t7;
  x[61] = 0.0;
  x[62] = 0.0;
  x[63] = 0.0;
  x[64] = 0.0;
  x[65] = 0.0;
  x[66] = 0.0;
  x[67] = 0.0;
  x[68] = 0.0;
  x[69] = 0.0;
  x[70] = t4;
  x[71] = t36;
  x[72] = 0.0;
  x[73] = 0.0;
  x[74] = 0.0;
  x[75] = 0.0;
  x[76] = 0.0;
  x[77] = 0.0;
  x[78] = 0.0;
  x[79] = 0.0;
  x[80] = t7;
  memcpy(&b_MI[0], &x[0], 81U * sizeof(double));
}

/* End of code generation (MI.c) */
