/*
 * S2V0.c
 *
 * Code generation for function 'S2V0'
 *
 */

/* Include files */
#include "rt_nonfinite.h"
#include "Afunc.h"
#include "Efunc.h"
#include "J.h"
#include "MI.h"
#include "S0.h"
#include "S20.h"
#include "S2V0.h"
#include "SV0.h"
#include "V0.h"
#include "Y0.h"
#include "d2AdPhi2.h"
#include "d2AdPhidTheta.h"
#include "d2AdTheta2.h"
#include "d2AdThetadPhi.h"
#include "d2EdPhi2.h"
#include "d2EdPhidTheta.h"
#include "d2EdTheta2.h"
#include "d2EdThetadPhi.h"
#include "d2fdTheta2.h"
#include "dAdPhi.h"
#include "dAdTheta.h"
#include "dEdPhi.h"
#include "dEdTheta.h"
#include "dFdTheta.h"
#include "reactionFlux.h"
#include "systemJacobian.h"
#include "rdivide.h"
#include "reactionFlux_rtwutil.h"

/* Function Definitions */
void S2V0(const double in1[6], double out1[108])
{
  double t2;
  double t4;
  double t5;
  double t6;
  double t7;
  double t9;
  double t11;
  double t12;
  double t13;
  double t16;
  double t17;
  double t18;
  double t19;
  double t20;
  double t23;
  double t24;
  double t25;
  double t26;
  double t30;
  double t31;
  double t32;
  double t36;
  double t37;
  double t38;
  double t39;
  double t40;
  double t42;
  double t43;
  double t44;
  double t45;
  double t52;
  double t53;
  double t56;
  double t59;
  double t60;
  double t61;
  double t125;
  double t62;
  double t126;
  double t64;
  double t67;
  double t68;
  double t70;
  double t129;
  double t75;
  double t130;
  double t84;
  double t86;
  double t94;
  double t101;
  double t102;
  double t103;
  double t104;
  double t111;
  double t118;
  double t119;
  double t124;
  double t128;
  double t134;
  double t137;
  double t139;
  double t146;
  double t147;
  double t148;
  double t149;
  double t155;
  double t156;
  double t159;
  double t162;
  double t172;
  double t187;
  double t182;
  double t186;
  double t193;
  double t192;
  double x[108];

  /* S2V0 */
  /*     OUT1 = S2V0(IN1) */
  /*     This function was generated by the Symbolic Math Toolbox version 6.1. */
  /*     25-Nov-2014 23:18:54 */
  t2 = sqrt(in1[0]);
  t4 = rdivide(1.0, sqrt(in1[0]));
  t5 = rdivide(1.0, t2);
  t6 = rdivide(1.0, in1[2]);
  t7 = rdivide(1.0, rt_powd_snf(in1[0], 1.5));
  t9 = rdivide(1.0, rt_powd_snf(t2, 3.0));
  t11 = (t2 * t7 * rdivide(1.0, 4.0) + t2 * t9 * rdivide(1.0, 4.0)) - t4 * t5 *
    rdivide(1.0, 2.0);
  t12 = in1[2] + in1[3];
  t13 = rdivide(1.0, t12);
  t16 = t2 * t4 * rdivide(1.0, 2.0) + t2 * t5 * rdivide(1.0, 2.0);
  t17 = rdivide(1.0, in1[2] * in1[2]);
  t18 = rdivide(1.0, t12 * t12);
  t19 = in1[1] * in1[1];
  t20 = rdivide(1.0, in1[3]);
  t23 = t2 * t4 * t19 * rdivide(1.0, 2.0) + t2 * t5 * t19 * rdivide(1.0, 2.0);
  t24 = t6 * t13 * t16 * rdivide(1.0, 2.0);
  t25 = in1[2] * in1[4];
  t26 = sqrt(t25);
  t30 = t2 * t2 + t26 * t26;
  t31 = rdivide(1.0, sqrt(t25));
  t32 = rdivide(1.0, t26);
  t36 = t6 * t13 * t20 * (in1[1] * t2 * t5 + in1[1] * t2 * t4) * rdivide(1.0,
    2.0);
  t37 = in1[1] * in1[4];
  t38 = in1[2] * in1[2];
  t39 = in1[4] * in1[4];
  t40 = sqrt(t37);
  t42 = rdivide(1.0, rt_powd_snf(t37, 1.5));
  t43 = rdivide(1.0, t40);
  t44 = rdivide(1.0, sqrt(t37));
  t45 = rdivide(1.0, rt_powd_snf(t40, 3.0));
  t52 = ((((in1[1] * t26 * t26 * 2.0 + in1[1] * t2 * t2 * 2.0) + in1[4] * t38 *
           t40 * t44 * rdivide(1.0, 2.0)) + in1[4] * t38 * t40 * t43 * rdivide
          (1.0, 2.0)) + in1[2] * in1[3] * in1[4] * t40 * t44 * rdivide(1.0, 2.0))
    + in1[2] * in1[3] * in1[4] * t40 * t43 * rdivide(1.0, 2.0);
  t53 = rdivide(1.0, in1[3] * in1[3]);
  t56 = in1[4] * t26 * t31 * rdivide(1.0, 2.0) + in1[4] * t26 * t32 * rdivide
    (1.0, 2.0);
  t59 = in1[2] * t26 * t31 * rdivide(1.0, 2.0) + in1[2] * t26 * t32 * rdivide
    (1.0, 2.0);
  t60 = rdivide(1.0, rt_powd_snf(t26, 3.0));
  t61 = rdivide(1.0, rt_powd_snf(t25, 1.5));
  t125 = in1[1] * t6 * t16 * t18 * rdivide(1.0, 2.0);
  t62 = -t125 - in1[1] * t13 * t16 * t17 * rdivide(1.0, 2.0);
  t126 = t6 * t18 * t30 * rdivide(1.0, 2.0);
  t64 = (t6 * t13 * t56 * rdivide(1.0, 2.0) - t126) - t13 * t17 * t30 * rdivide
    (1.0, 2.0);
  t67 = (t26 * t39 * t60 * rdivide(1.0, 4.0) + t26 * t39 * t61 * rdivide(1.0,
          4.0)) - t31 * t32 * t39 * rdivide(1.0, 2.0);
  t68 = rdivide(1.0, rt_powd_snf(in1[2], 3.0));
  t37 = rdivide(1.0, rt_powd_snf(t12, 3.0));
  t70 = in1[1] * t6 * t30 * t37;
  t12 = (((t26 * t32 * rdivide(1.0, 2.0) + t26 * t31 * rdivide(1.0, 2.0)) + in1
          [2] * in1[4] * t31 * t32 * rdivide(1.0, 2.0)) - in1[2] * in1[4] * t26 *
         t60 * rdivide(1.0, 4.0)) - in1[2] * in1[4] * t26 * t61 * rdivide(1.0,
    4.0);
  t129 = t6 * t18 * t20 * t23 * rdivide(1.0, 2.0);
  t75 = -t129 - t13 * t17 * t20 * t23 * rdivide(1.0, 2.0);
  t130 = t6 * t18 * t20 * t52 * rdivide(1.0, 2.0);
  t84 = (t6 * t13 * t20 * (((((in1[1] * in1[4] * t26 * t32 + in1[2] * in1[4] *
              t40 * t43) + in1[3] * in1[4] * t40 * t43 * rdivide(1.0, 2.0)) +
            in1[1] * in1[4] * t26 * t31) + in1[2] * in1[4] * t40 * t44) + in1[3]
          * in1[4] * t40 * t44 * rdivide(1.0, 2.0)) * rdivide(1.0, 2.0) - t130)
    - t13 * t17 * t20 * t52 * rdivide(1.0, 2.0);
  t25 = in1[3] * in1[5];
  t86 = sqrt(t25);
  t94 = ((((t2 * t2 * t19 + t38 * t86 * t86) + t19 * t26 * t26) + t38 * t40 *
          t40) + in1[2] * in1[3] * t86 * t86) + in1[2] * in1[3] * t40 * t40;
  t101 = ((((in1[2] * t86 * t86 * 2.0 + in1[3] * t86 * t86) + in1[2] * t40 * t40
            * 2.0) + in1[3] * t40 * t40) + in1[4] * t19 * t26 * t31 * rdivide
          (1.0, 2.0)) + in1[4] * t19 * t26 * t32 * rdivide(1.0, 2.0);
  t102 = rdivide(1.0, t86);
  t103 = rdivide(1.0, sqrt(t25));
  t104 = t6 * t20 * t37 * t94;
  t111 = ((((in1[2] * t86 * t86 + in1[2] * t40 * t40) + in1[5] * t38 * t86 *
            t103 * rdivide(1.0, 2.0)) + in1[5] * t38 * t86 * t102 * rdivide(1.0,
            2.0)) + in1[2] * in1[3] * in1[5] * t86 * t103 * rdivide(1.0, 2.0)) +
    in1[2] * in1[3] * in1[5] * t86 * t102 * rdivide(1.0, 2.0);
  t118 = ((((in1[2] * t19 * t26 * t31 * rdivide(1.0, 2.0) + in1[1] * t38 * t40 *
             t44 * rdivide(1.0, 2.0)) + in1[2] * t19 * t26 * t32 * rdivide(1.0,
             2.0)) + in1[1] * t38 * t40 * t43 * rdivide(1.0, 2.0)) + in1[2] *
          in1[3] * in1[1] * t40 * t44 * rdivide(1.0, 2.0)) + in1[2] * in1[3] *
    in1[1] * t40 * t43 * rdivide(1.0, 2.0);
  t119 = in1[3] * in1[3];
  t124 = ((in1[2] * t86 * t103 * t119 * rdivide(1.0, 2.0) + in1[3] * t38 * t86 *
           t103 * rdivide(1.0, 2.0)) + in1[2] * t86 * t102 * t119 * rdivide(1.0,
           2.0)) + in1[3] * t38 * t86 * t102 * rdivide(1.0, 2.0);
  t128 = (t70 + in1[1] * t17 * t18 * t30 * rdivide(1.0, 2.0)) - in1[1] * t6 *
    t18 * t56 * rdivide(1.0, 2.0);
  t134 = t6 * t13 * t20 * (in1[2] * in1[4] * t40 * t43 * rdivide(1.0, 2.0) +
    in1[2] * in1[4] * t40 * t44 * rdivide(1.0, 2.0)) * rdivide(1.0, 2.0);
  t137 = in1[2] * in1[5] * t86 * t102;
  t139 = in1[2] * in1[5] * t86 * t103;
  t146 = (((((((t104 + t6 * t13 * t20 * (((((t86 * t86 + t40 * t40) + t137) +
    in1[3] * in1[5] * t86 * t102 * rdivide(1.0, 2.0)) + t139) + in1[3] * in1[5] *
    t86 * t103 * rdivide(1.0, 2.0)) * rdivide(1.0, 2.0)) + t6 * t18 * t53 * t94 *
               rdivide(1.0, 2.0)) + t17 * t18 * t20 * t94 * rdivide(1.0, 2.0)) +
             t13 * t17 * t53 * t94 * rdivide(1.0, 2.0)) - t6 * t18 * t20 * t101 *
            rdivide(1.0, 2.0)) - t6 * t18 * t20 * t111 * rdivide(1.0, 2.0)) -
          t13 * t17 * t20 * t111 * rdivide(1.0, 2.0)) - t6 * t13 * t53 * t101 *
    rdivide(1.0, 2.0);
  t147 = in1[5] * in1[5];
  t148 = rdivide(1.0, rt_powd_snf(t25, 1.5));
  t149 = rdivide(1.0, rt_powd_snf(t86, 3.0));
  t37 = in1[2] * in1[3] * t86 * t102;
  t25 = in1[2] * in1[3] * t86 * t103;
  t155 = t6 * t12 * rdivide(1.0, 2.0) - t17 * t59 * rdivide(1.0, 2.0);
  t156 = t6 * t13 * t59 * rdivide(1.0, 2.0);
  t159 = in1[1] * t6 * t18 * t59 * rdivide(1.0, 2.0);
  t12 = (in1[1] * t6 * t13 * t12 * rdivide(1.0, 2.0) - t159) - in1[1] * t13 *
    t17 * t59 * rdivide(1.0, 2.0);
  t162 = (t26 * t38 * t60 * rdivide(1.0, 4.0) + t26 * t38 * t61 * rdivide(1.0,
           4.0)) - t31 * t32 * t38 * rdivide(1.0, 2.0);
  t172 = t6 * t13 * t20 * (((((((((((t38 * t40 * t43 * rdivide(1.0, 2.0) + t38 *
    t40 * t44 * rdivide(1.0, 2.0)) + in1[2] * in1[1] * t26 * t32) + in1[2] *
    in1[3] * t40 * t43 * rdivide(1.0, 2.0)) + in1[2] * in1[1] * t26 * t31) +
    in1[2] * in1[3] * t40 * t44 * rdivide(1.0, 2.0)) + in1[1] * in1[4] * t38 *
    t43 * t44 * rdivide(1.0, 2.0)) + in1[2] * in1[3] * in1[1] * in1[4] * t43 *
    t44 * rdivide(1.0, 2.0)) - in1[1] * in1[4] * t38 * t40 * t42 * rdivide(1.0,
    4.0)) - in1[1] * in1[4] * t38 * t40 * t45 * rdivide(1.0, 4.0)) - in1[2] *
    in1[3] * in1[1] * in1[4] * t40 * t42 * rdivide(1.0, 4.0)) - in1[2] * in1[3] *
    in1[1] * in1[4] * t40 * t45 * rdivide(1.0, 4.0)) * rdivide(1.0, 2.0);
  t187 = t6 * t18 * t20 * t118 * rdivide(1.0, 2.0);
  t182 = (t6 * t13 * t20 * ((((((((t19 * t26 * t32 * rdivide(1.0, 2.0) + t19 *
    t26 * t31 * rdivide(1.0, 2.0)) + in1[2] * in1[1] * t40 * t43) + in1[3] *
    in1[1] * t40 * t43 * rdivide(1.0, 2.0)) + in1[2] * in1[1] * t40 * t44) +
              in1[3] * in1[1] * t40 * t44 * rdivide(1.0, 2.0)) + in1[2] * in1[4]
             * t19 * t31 * t32 * rdivide(1.0, 2.0)) - in1[2] * in1[4] * t19 *
            t26 * t60 * rdivide(1.0, 4.0)) - in1[2] * in1[4] * t19 * t26 * t61 *
           rdivide(1.0, 4.0)) * rdivide(1.0, 2.0) - t187) - t13 * t17 * t20 *
    t118 * rdivide(1.0, 2.0);
  t186 = t6 * t13 * t20 * (in1[2] * in1[1] * t40 * t43 * rdivide(1.0, 2.0) +
    in1[2] * in1[1] * t40 * t44 * rdivide(1.0, 2.0)) * rdivide(1.0, 2.0);
  t193 = t6 * t18 * t20 * t124 * rdivide(1.0, 2.0);
  t192 = (t6 * t13 * t20 * (((t37 + t25) + t86 * t102 * t119 * rdivide(1.0, 2.0))
           + t86 * t103 * t119 * rdivide(1.0, 2.0)) * rdivide(1.0, 2.0) - t193)
    - t13 * t17 * t20 * t124 * rdivide(1.0, 2.0);
  t37 = t6 * t13 * t20 * (((((((((t37 + t25) + t38 * t86 * t102 * rdivide(1.0,
    2.0)) + t38 * t86 * t103 * rdivide(1.0, 2.0)) + in1[2] * in1[5] * t102 *
    t103 * t119 * rdivide(1.0, 2.0)) + in1[3] * in1[5] * t38 * t102 * t103 *
    rdivide(1.0, 2.0)) - in1[2] * in1[5] * t86 * t119 * t149 * rdivide(1.0, 4.0))
    - in1[2] * in1[5] * t86 * t119 * t148 * rdivide(1.0, 4.0)) - in1[3] * in1[5]
    * t38 * t86 * t149 * rdivide(1.0, 4.0)) - in1[3] * in1[5] * t38 * t86 * t148
    * rdivide(1.0, 4.0)) * rdivide(1.0, 2.0);
  x[0] = t6 * t11 * rdivide(-1.0, 2.0);
  x[1] = in1[1] * t6 * t11 * t13 * rdivide(-1.0, 2.0);
  x[2] = t6 * t13 * t20 * ((t4 * t5 * t19 * rdivide(-1.0, 2.0) + t2 * t7 * t19 *
    rdivide(1.0, 4.0)) + t2 * t9 * t19 * rdivide(1.0, 4.0)) * rdivide(-1.0, 2.0);
  x[3] = 0.0;
  x[4] = t24;
  x[5] = t36;
  x[6] = t16 * t17 * rdivide(-1.0, 2.0);
  x[7] = t62;
  x[8] = t75;
  x[9] = 0.0;
  x[10] = -t125;
  x[11] = -t129 - t6 * t13 * t23 * t53 * rdivide(1.0, 2.0);
  x[12] = 0.0;
  x[13] = 0.0;
  x[14] = 0.0;
  x[15] = 0.0;
  x[16] = 0.0;
  x[17] = 0.0;
  x[18] = 0.0;
  x[19] = t24;
  x[20] = t36;
  x[21] = 0.0;
  x[22] = 0.0;
  x[23] = t6 * t13 * t20 * (((((((t2 * t2 * 2.0 + t26 * t26 * 2.0) - t38 * t39 *
    t40 * t42 * rdivide(1.0, 4.0)) - t38 * t39 * t40 * t45 * rdivide(1.0, 4.0))
    + t38 * t39 * t43 * t44 * rdivide(1.0, 2.0)) - in1[2] * in1[3] * t39 * t40 *
    t42 * rdivide(1.0, 4.0)) - in1[2] * in1[3] * t39 * t40 * t45 * rdivide(1.0,
    4.0)) + in1[2] * in1[3] * t39 * t43 * t44 * rdivide(1.0, 2.0)) * rdivide(1.0,
    2.0);
  x[24] = 0.0;
  x[25] = t64;
  x[26] = t84;
  x[27] = 0.0;
  x[28] = -t126;
  x[29] = (-t130 + t134) - t6 * t13 * t52 * t53 * rdivide(1.0, 2.0);
  x[30] = 0.0;
  x[31] = t156;
  x[32] = t172;
  x[33] = 0.0;
  x[34] = 0.0;
  x[35] = 0.0;
  x[36] = t16 * t17 * rdivide(-1.0, 2.0);
  x[37] = t62;
  x[38] = t75;
  x[39] = 0.0;
  x[40] = t64;
  x[41] = t84;
  x[42] = (t6 * t67 * rdivide(-1.0, 2.0) - t17 * t56) + t30 * t68;
  x[43] = ((((t70 + in1[1] * t17 * t18 * t30) - in1[1] * t6 * t18 * t56) - in1[1]
            * t6 * t13 * t67 * rdivide(1.0, 2.0)) - in1[1] * t13 * t17 * t56) +
    in1[1] * t13 * t30 * t68;
  x[44] = ((((t104 - t6 * t18 * t20 * t101) + t17 * t18 * t20 * t94) - t13 * t17
            * t20 * t101) + t13 * t20 * t68 * t94) + t6 * t13 * t20 * ((((t40 *
    t40 * 2.0 + t86 * t86 * 2.0) + t19 * t31 * t32 * t39 * rdivide(1.0, 2.0)) -
    t19 * t26 * t39 * t60 * rdivide(1.0, 4.0)) - t19 * t26 * t39 * t61 * rdivide
    (1.0, 4.0)) * rdivide(1.0, 2.0);
  x[45] = 0.0;
  x[46] = t128;
  x[47] = t146;
  x[48] = t155;
  x[49] = t12;
  x[50] = t182;
  x[51] = 0.0;
  x[52] = 0.0;
  x[53] = t192;
  x[54] = 0.0;
  x[55] = in1[1] * t6 * t16 * t18 * rdivide(-1.0, 2.0);
  x[56] = t6 * t18 * t20 * t23 * rdivide(-1.0, 2.0) - t6 * t13 * t23 * t53 *
    rdivide(1.0, 2.0);
  x[57] = 0.0;
  x[58] = t6 * t18 * t30 * rdivide(-1.0, 2.0);
  x[59] = (t134 - t6 * t18 * t20 * t52 * rdivide(1.0, 2.0)) - t6 * t13 * t52 *
    t53 * rdivide(1.0, 2.0);
  x[60] = 0.0;
  x[61] = t128;
  x[62] = t146;
  x[63] = 0.0;
  x[64] = t70;
  x[65] = ((((t104 - t6 * t18 * t20 * t111) + t6 * t18 * t53 * t94) - t6 * t13 *
            t53 * t111) + t6 * t13 * t20 * (((((((t137 + t139) + t38 * t102 *
    t103 * t147 * rdivide(1.0, 2.0)) - t38 * t86 * t147 * t149 * rdivide(1.0,
    4.0)) - t38 * t86 * t147 * t148 * rdivide(1.0, 4.0)) + in1[2] * in1[3] *
              t102 * t103 * t147 * rdivide(1.0, 2.0)) - in1[2] * in1[3] * t86 *
             t147 * t149 * rdivide(1.0, 4.0)) - in1[2] * in1[3] * t86 * t147 *
            t148 * rdivide(1.0, 4.0)) * rdivide(1.0, 2.0)) + rdivide(1.0,
    rt_powd_snf(in1[3], 3.0)) * t6 * t13 * t94;
  x[66] = 0.0;
  x[67] = -t159;
  x[68] = (t186 - t187) - t6 * t13 * t53 * t118 * rdivide(1.0, 2.0);
  x[69] = 0.0;
  x[70] = 0.0;
  x[71] = (-t193 + t37) - t6 * t13 * t53 * t124 * rdivide(1.0, 2.0);
  x[72] = 0.0;
  x[73] = 0.0;
  x[74] = 0.0;
  x[75] = 0.0;
  x[76] = t156;
  x[77] = t172;
  x[78] = t155;
  x[79] = t12;
  x[80] = t182;
  x[81] = 0.0;
  x[82] = in1[1] * t6 * t18 * t59 * rdivide(-1.0, 2.0);
  x[83] = (t186 - t6 * t18 * t20 * t118 * rdivide(1.0, 2.0)) - t6 * t13 * t53 *
    t118 * rdivide(1.0, 2.0);
  x[84] = t6 * t162 * rdivide(-1.0, 2.0);
  x[85] = in1[1] * t6 * t13 * t162 * rdivide(-1.0, 2.0);
  x[86] = t6 * t13 * t20 * ((((((((t19 * t31 * t32 * t38 * rdivide(-1.0, 2.0) +
    t19 * t38 * t40 * t42 * rdivide(1.0, 4.0)) + t19 * t38 * t40 * t45 * rdivide
                                  (1.0, 4.0)) + t19 * t26 * t38 * t60 * rdivide
    (1.0, 4.0)) - t19 * t38 * t43 * t44 * rdivide(1.0, 2.0)) + t19 * t26 * t38 *
    t61 * rdivide(1.0, 4.0)) + in1[2] * in1[3] * t19 * t40 * t42 * rdivide(1.0,
    4.0)) + in1[2] * in1[3] * t19 * t40 * t45 * rdivide(1.0, 4.0)) - in1[2] *
    in1[3] * t19 * t43 * t44 * rdivide(1.0, 2.0)) * rdivide(-1.0, 2.0);
  x[87] = 0.0;
  x[88] = 0.0;
  x[89] = 0.0;
  x[90] = 0.0;
  x[91] = 0.0;
  x[92] = 0.0;
  x[93] = 0.0;
  x[94] = 0.0;
  x[95] = 0.0;
  x[96] = 0.0;
  x[97] = 0.0;
  x[98] = t192;
  x[99] = 0.0;
  x[100] = 0.0;
  x[101] = (t37 - t6 * t18 * t20 * t124 * rdivide(1.0, 2.0)) - t6 * t13 * t53 *
    t124 * rdivide(1.0, 2.0);
  x[102] = 0.0;
  x[103] = 0.0;
  x[104] = 0.0;
  x[105] = 0.0;
  x[106] = 0.0;
  x[107] = t6 * t13 * t20 * (((((t38 * t102 * t103 * t119 * rdivide(-1.0, 2.0) +
    t38 * t86 * t119 * t149 * rdivide(1.0, 4.0)) + t38 * t86 * t119 * t148 *
    rdivide(1.0, 4.0)) - in1[2] * in1[3] * t102 * t103 * t119 * rdivide(1.0, 2.0))
    + in1[2] * in1[3] * t86 * t119 * t149 * rdivide(1.0, 4.0)) + in1[2] * in1[3]
    * t86 * t119 * t148 * rdivide(1.0, 4.0)) * rdivide(-1.0, 2.0);
  memcpy(&out1[0], &x[0], 108U * sizeof(double));
}

/* End of code generation (S2V0.c) */
