/*
 * systemJacobian.c
 *
 * Code generation for function 'systemJacobian'
 *
 */

/* Include files */
#include "rt_nonfinite.h"
#include "Afunc.h"
#include "Efunc.h"
#include "J.h"
#include "MI.h"
#include "S0.h"
#include "S20.h"
#include "S2V0.h"
#include "SV0.h"
#include "V0.h"
#include "Y0.h"
#include "d2AdPhi2.h"
#include "d2AdPhidTheta.h"
#include "d2AdTheta2.h"
#include "d2AdThetadPhi.h"
#include "d2EdPhi2.h"
#include "d2EdPhidTheta.h"
#include "d2EdTheta2.h"
#include "d2EdThetadPhi.h"
#include "d2fdTheta2.h"
#include "dAdPhi.h"
#include "dAdTheta.h"
#include "dEdPhi.h"
#include "dEdTheta.h"
#include "dFdTheta.h"
#include "reactionFlux.h"
#include "systemJacobian.h"

/* Function Definitions */
void systemJacobian(const double in1[2], double t, const double in3[6], double
                    b_systemJacobian[81])
{
  double t2;
  double t3;
  double t5;
  double t6;
  double t8;
  double t9;
  double x[81];
  (void)t;

  /* SYSTEMJACOBIAN */
  /*     SYSTEMJACOBIAN = SYSTEMJACOBIAN(IN1,T,IN3) */
  /*     This function was generated by the Symbolic Math Toolbox version 6.1. */
  /*     25-Nov-2014 23:18:32 */
  t2 = in3[2] * in1[0];
  t3 = sqrt(t2);
  t5 = in3[1] * in1[0];
  t6 = sqrt(t5);
  t8 = in3[3] * in1[1];
  t9 = sqrt(t8);
  x[0] = -in3[2];
  x[1] = in3[1];
  x[2] = in3[2] * t3 * 0.5 / t3 + in3[2] / sqrt(t2) * t3 * 0.5;
  x[3] = 0.0;
  x[4] = in3[1] * t6 * 0.5 / t6 + in3[1] / sqrt(t5) * t6 * 0.5;
  x[5] = 0.0;
  x[6] = 0.0;
  x[7] = 0.0;
  x[8] = 0.0;
  x[9] = 0.0;
  x[10] = -in3[3];
  x[11] = 0.0;
  x[12] = 0.0;
  x[13] = in3[3] * t9 * 0.5 / t9 + in3[3] / sqrt(t8) * t9 * 0.5;
  x[14] = 0.0;
  x[15] = 0.0;
  x[16] = 0.0;
  x[17] = 0.0;
  x[18] = 0.0;
  x[19] = 0.0;
  x[20] = in3[2] * -2.0;
  x[21] = in3[1];
  x[22] = 0.0;
  x[23] = 0.0;
  x[24] = 0.0;
  x[25] = 0.0;
  x[26] = 0.0;
  x[27] = 0.0;
  x[28] = 0.0;
  x[29] = 0.0;
  x[30] = 0.0;
  x[31] = in3[1];
  x[32] = 0.0;
  x[33] = 0.0;
  x[34] = 0.0;
  x[35] = 0.0;
  x[36] = 0.0;
  x[37] = 0.0;
  x[38] = 0.0;
  x[39] = 0.0;
  x[40] = in3[3] * -2.0;
  x[41] = 0.0;
  x[42] = 0.0;
  x[43] = 0.0;
  x[44] = 0.0;
  x[45] = 0.0;
  x[46] = 0.0;
  x[47] = 0.0;
  x[48] = 0.0;
  x[49] = 0.0;
  x[50] = -in3[2];
  x[51] = in3[1];
  x[52] = 0.0;
  x[53] = 0.0;
  x[54] = 0.0;
  x[55] = 0.0;
  x[56] = 0.0;
  x[57] = 0.0;
  x[58] = 0.0;
  x[59] = 0.0;
  x[60] = -in3[3];
  x[61] = 0.0;
  x[62] = 0.0;
  x[63] = 0.0;
  x[64] = 0.0;
  x[65] = 0.0;
  x[66] = 0.0;
  x[67] = 0.0;
  x[68] = 0.0;
  x[69] = 0.0;
  x[70] = -in3[2];
  x[71] = in3[1];
  x[72] = 0.0;
  x[73] = 0.0;
  x[74] = 0.0;
  x[75] = 0.0;
  x[76] = 0.0;
  x[77] = 0.0;
  x[78] = 0.0;
  x[79] = 0.0;
  x[80] = -in3[3];
  memcpy(&b_systemJacobian[0], &x[0], 81U * sizeof(double));
}

/* End of code generation (systemJacobian.c) */
