/*
 * V0.c
 *
 * Code generation for function 'V0'
 *
 */

/* Include files */
#include "rt_nonfinite.h"
#include "Afunc.h"
#include "Efunc.h"
#include "J.h"
#include "MI.h"
#include "S0.h"
#include "S20.h"
#include "S2V0.h"
#include "SV0.h"
#include "V0.h"
#include "Y0.h"
#include "d2AdPhi2.h"
#include "d2AdPhidTheta.h"
#include "d2AdTheta2.h"
#include "d2AdThetadPhi.h"
#include "d2EdPhi2.h"
#include "d2EdPhidTheta.h"
#include "d2EdTheta2.h"
#include "d2EdThetadPhi.h"
#include "d2fdTheta2.h"
#include "dAdPhi.h"
#include "dAdTheta.h"
#include "dEdPhi.h"
#include "dEdTheta.h"
#include "dFdTheta.h"
#include "reactionFlux.h"
#include "systemJacobian.h"

/* Function Definitions */
void V0(const double in1[6], double out1[3])
{
  double t2;
  double t4;
  double t5;
  double t10;
  double t12;
  double t14;
  double t15;
  double t16;
  double t18;

  /* V0 */
  /*     OUT1 = V0(IN1) */
  /*     This function was generated by the Symbolic Math Toolbox version 6.1. */
  /*     25-Nov-2014 23:18:33 */
  t2 = sqrt(in1[0]);
  t4 = sqrt(in1[2] * in1[4]);
  t5 = 1.0 / in1[2];
  t10 = t2 * t2 + t4 * t4;
  t12 = 1.0 / (in1[2] + in1[3]);
  t14 = sqrt(in1[3] * in1[5]);
  t15 = in1[1] * in1[1];
  t16 = in1[2] * in1[2];
  t18 = sqrt(in1[1] * in1[4]);
  out1[0] = t5 * t10 * 0.5;
  out1[1] = in1[1] * t5 * t10 * t12 * 0.5;
  out1[2] = t5 * t12 * (((((t2 * t2 * t15 + t4 * t4 * t15) + t14 * t16 * t14) +
    t16 * t18 * t18) + in1[2] * in1[3] * t14 * t14) + in1[2] * in1[3] * t18 *
                        t18) * 0.5 / in1[3];
}

/* End of code generation (V0.c) */
